system:
  no_shared_fs: ${experiment.runner.no_shared_fs}
  num_workers: 1
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 2
  context_parallel_size: 1
  disable_bias_linear: true
  reset_position_ids: true
  reset_attention_mask: true
  qk_layernorm: true
  distributed_backend: flagcx
  finetune: true
  no_initialization: true
  precision:
    bf16: true
    attention_softmax_in_fp32: true
    accumulate_allreduce_grads_in_fp32: true
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
  checkpoint:
    save_interval: ${experiment.save_steps}
    load: ${experiment.load}
    ckpt_format: ${experiment.ckpt_format}

model:
  transformer_impl: local
  enable_flag_gems: True
  legacy_tokenizer: True
  num_layers: 2
  hidden_size: 5120
  ffn_hidden_size: 17408
  kv_channels: 128
  group_query_attention: true
  num_attention_heads: 40
  num_query_groups: 8 # num_key_value_heads
  seq_length: 10
  max_position_embeddings: 40960
  norm_epsilon: 1e-6
  use_rotary_position_embeddings: true
  rotary_base: 1000000
  swiglu: true
  normalization: RMSNorm
  init_method_std: 0.02
  attention_dropout: 0.0
  hidden_dropout: 0.0
  clip_grad: 1.0
  position_embedding_type: rope
  untie_embeddings_and_output_weights: true
  no_position_embedding: true
  no_rope_fusion: true
  no_persist_layer_norm: true
  no_gradient_accumulation_fusion: true
  no_masked_softmax_fusion: true
  no_bias_dropout_fusion: true
  no_bias_swiglu_fusion: true
  no_bias_gelu_fusion: true

  # training
  seed: ${experiment.seed}
  micro_batch_size: 1
  global_batch_size: 2
  eval_iters: 0
  train_iters: 10

  optimizer:
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 3.0e-3
      min_lr: 3.0e-4
      lr_warmup_fraction: .1
      lr_decay_style: cosine


data:
  data_path: /login_home/malin/datasets/llama3-datasets/wudao_llama3bpe_content_document
  split: 1
  no_mmap_bin_files: true
  tokenizer:
    tokenizer_type: QwenTokenizerFS
    tokenizer_path: /login_home/malin/datasets/Qwen3-14B
    vocab_size: 151851
    make_vocab_size_divisible_by: 64
