defaults:
  - _self_
  - train: 14b

experiment:
  exp_name: Qwen3-14b-Train
  seed: 42
  save_steps: 10000
  load: /login_home/malin/workspace/FlagOS/ckpts/qwen3_14b_mp4
  exp_dir: ./outputs/outputs_qwen3_14b
  ckpt_format: torch
  task:
    type: train
    backend: megatron
    entrypoint: flagscale/train/megatron/train_gpt.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: ./examples/qwen3/conf/hostfile.txt
    master_port: 8889
    #ssh_port: 2222
  cmds:
    before_start: ulimit -n 1048576
  envs:
    #LOGLEVEL: "DEBUG"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    TXDA_VISIBLE_DEVICES: "24,25,26,27,28,29,30,31"
    MG_PLATFORM: "txda"

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
